name: Update LevelIndex every 5 minutes with Slack notification

on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 20 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-level:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_version.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json
          git diff --cached --quiet || git commit -m "Auto update LevelIndex"
          git push

      - name: Notify Slack
        if: always()  # toujours envoyer, succès ou échec
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
